/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_joshuad_waveformjni_HWaveOut */

#ifndef _Included_net_joshuad_waveformjni_HWaveOut
#define _Included_net_joshuad_waveformjni_HWaveOut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutGetNumDevs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutGetNumDevs
  (JNIEnv *, jclass);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutGetPitch
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutGetPitch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutGetPlaybackRate
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutGetPlaybackRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutGetVolume
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutGetVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutOpen
 * Signature: (IIIII)[J
 */
JNIEXPORT jlongArray JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutOpen
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutPause
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutPause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutPrepareHeader
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutPrepareHeader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutReset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutRestart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutRestart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutSetPitch
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutSetPitch
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutSetPlaybackRate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutSetPlaybackRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutSetVolume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutSetVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutUnprepareHeader
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutUnprepareHeader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    waveOutWrite
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_waveOutWrite
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    createHeader
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_net_joshuad_waveformjni_HWaveOut_createHeader
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    destroyHeader
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_joshuad_waveformjni_HWaveOut_destroyHeader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_waveformjni_HWaveOut
 * Method:    getHeaderFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_waveformjni_HWaveOut_getHeaderFlags
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
